name: Build and deploy Python app to Azure Web App - CRUD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          # Instala compiladores y herramientas esenciales
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev g++ python3-dev build-essential
          
          # Configura el repositorio de Microsoft para ODBC
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/20.04/prod focal main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
          
          # Instala el driver ODBC
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
          
          # Verifica la instalación del driver
          odbcinst -j

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create runtime.txt
        run: echo "python-3.11" > runtime.txt

      - name: Zip artifact
        run: zip -r release.zip . -x 'venv/*' '*.git*' '*.github/*' '.env*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 'Delay before deployment'
        run: sleep 120s

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CRUD'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_60C717F1C5584383B0EA13430B50A3BB }}
          package: release.zip