name: Build and deploy Python app to Azure Web App - CRUD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.9' # Azure App Service actualmente soporta hasta 3.9
  WEBAPP_PORT: 8001     # Puerto que usa tu aplicación

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install waitress gunicorn # Asegura instalación de servidores WSGI

      - name: Create startup.sh
        run: |
          cat > startup.sh << 'EOF'
          #!/bin/bash
          # Mata procesos previos
          pkill -f "python.*app.py" || true
          pkill -f gunicorn || true
          sleep 3
          
          # Inicia la aplicación
          cd /home/site/wwwroot
          python -c "from waitress import serve; from app import app; serve(app, host='0.0.0.0', port=${{ env.WEBAPP_PORT }})"
          EOF
          chmod +x startup.sh

      - name: Zip artifacts
        run: |
          zip -r deploy.zip . -x '*.git*' '*.env*' 'venv/*'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CRUD'
          slot-name: 'Production'
          package: deploy.zip
          app-settings: |
            WEBSITES_PORT=${{ env.WEBAPP_PORT }}
            SCM_DO_BUILD_DURING_DEPLOYMENT=true
